db.janusgraph.index.search {
  backend = elasticsearch
  hostname = ["elasticsearch"]
  index-name = thehive
  elasticsearch.http.auth {
    type = "basic"
    basic {
      username = "elastic"
      password = "vFaoD3slE920qkl9GLYfoRdK8CnLGRlMb658aSldeSHNt7khhAmeDADRupQ0Jd73"
    }
  }
}
