HOSTNAME=mail.cyberhome.es
FIRST_MAIL_DOMAIN=cyberhome.es	
FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=SkyShowtime:Prime:1992
MLMMJADMIN_API_TOKEN=vAehYhxZULRWHVs9cPoe7RGLdCPxt8UNseM6QJhVBfM=
ROUNDCUBE_DES_KEY=M+p2pzlRyL34dS9/tlHh2dd3jzrwf8Vf
